apiVersion: v1
kind: Secret
metadata:
  name: {{ include "eval-pd-report-service.fullname" . }}-env
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  {{- range $key, $value := .Values.env }}
  {{- if $value }}
  {{ $key }}: {{ toYaml $value | b64enc }}
  {{- else }}
  {{ $key }}: ""
  {{- end }}
  {{- end }}
