{{- if .Values.secretProvider.enabled -}}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
    name: {{ include "eval-pd-report-service.fullname" . }}-spc
    namespace: {{ .Values.namespace }}
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: {{ .Values.secretProvider.objectName | default .Chart.Name }}/{{ .Release.Namespace }}/service-credentials
        objectType: "secretsmanager"
        jmesPath:
{{- if .Values.secretProvider.jmesPaths }}
{{- range .Values.secretProvider.jmesPaths }}
          - path: "{{ .path }}"
            objectAlias: "{{ .objectAlias }}"
{{- end }}
{{- else }}
{{- range $key, $val := .Values.secretProvider.secretKeys }}
          - path: "{{ $val }}"
            objectAlias: "{{ $val }}"
{{- end }}
{{- end }}
  secretObjects:
  - secretName: {{ .Chart.Name }}
    type: {{ default "Opaque" .Values.secretProvider.k8sSecret.type }}
    data:
{{- if .Values.secretProvider.k8sSecret.data }}
{{- range .Values.secretProvider.k8sSecret.data }}
      - objectName: "{{ .objectName }}"
        key: "{{ .key }}"
{{- end }}
{{- else }}
{{- range $key, $val := .Values.secretProvider.secretKeys }}
      - objectName: "{{ $val }}"
        key: "{{ $val }}"
{{- end }}
{{- end }}
{{- end }}
