# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
namespace: staging
istioHostDomain: api.stage.evplus.com

nameOverride: staging-eval-pd-report-service
fullnameOverride: staging-eval-pd-report-service

env:
  SQS_QUEUE_NAME: ev-plus-reporting-stage-queue
  EMAIL_FROM_ADDRESS: noreply@evplus.com
  OIDC_ISSUER_URI: https://stage-oidc.evplus.com
  S3_BUCKET: ev-plus-reports-stage
