# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
namespace: develop
istioHostDomain: api-dev.goteachpoint.com

nameOverride: develop-eval-pd-report
fullnameOverride: develop-eval-pd-report

env:
  SQS_QUEUE_NAME: eval-pd-develop-report-service-queue
  EMAIL_FROM_ADDRESS: noreply@evplus.com
  OIDC_ISSUER_URI: https://dev-oidc.evplus.com
  S3_BUCKET: ev-plus-reports-dev
  SPRING_PROFILES_ACTIVE: dev
  SQS_QUEUE_URL: https://sqs.us-east-2.amazonaws.com/760612481786/eval-pd-develop-report-service-queue
