# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
namespace: production
istioHostDomain: tp1.goteachpoint.com

nameOverride: production-eval-pd-report
fullnameOverride: production-eval-pd-report

env:
  SQS_QUEUE_NAME: ev-plus-reporting-prod-queue
  EMAIL_FROM_ADDRESS: noreply@evplus.com
  OIDC_ISSUER_URI: https://oidc.evplus.com
  S3_BUCKET: ev-plus-reports-prod
