# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
namespace: production
istioHostDomain: tp1.goteachpoint.com

nameOverride: production-eval-pd-report
fullnameOverride: production-eval-pd-report

env:
  SQS_QUEUE_NAME: ev-plus-reporting-prod-queue
  EMAIL_FROM_ADDRESS: noreply@evplus.com
  OIDC_ISSUER_URI: https://tp1.goteachpoint.com/vector-eval/v2
  S3_BUCKET: tp1-userfiles
  SPRING_PROFILES_ACTIVE: prod
  SQS_QUEUE_URL: 
  NOTIFICATION_QUEUE_NAME: https://sqs.us-east-2.amazonaws.com/325923818481/tp1_Notifications.fifo
