# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
namespace: develop
istioHostDomain: api.develop.us-east-2.vsp-nonprod.com

nameOverride: develop-eval-pd-report
fullnameOverride: develop-eval-pd-report

env:
  SQS_QUEUE_NAME: eval-pd-develop-report-service-queue
  EMAIL_FROM_ADDRESS: noreply@evplus.com
  OIDC_ISSUER_URI: https://tp3a.goteachpoint.com/vector-eval/v2
  S3_BUCKET: files-tp3a-test
  SPRING_PROFILES_ACTIVE: dev
  SQS_QUEUE_URL: https://sqs.us-east-2.amazonaws.com/760612481786/eval-pd-develop-report-service-queue
  NOTIFICATION_QUEUE_NAME: https://sqs.us-east-2.amazonaws.com/370246022780/tp3a_Notifications.fifo
