# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
namespace: staging
istioHostDomain: api-stage.goteachpoint.com

nameOverride: staging-eval-pd-report
fullnameOverride: staging-eval-pd-report

env:
  SQS_QUEUE_NAME: ev-plus-reporting-stage-queue
  EMAIL_FROM_ADDRESS: noreply@evplus.com
  OIDC_ISSUER_URI: https://stage-oidc.evplus.com
  S3_BUCKET: ev-plus-reports-stage
  SPRING_PROFILES_ACTIVE: stage
  SQS_QUEUE_URL: https://sqs.us-east-2.amazonaws.com/760612481786/eval-pd-stage-report-service-queue 
  NOTIFICATION_QUEUE_NAME: https://sqs.us-east-2.amazonaws.com/370246022780/tp7_Notifications.fifo